spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jav_actress?useSSL=false&serverTimezone=UTC
    username: root
    password: menguer110804
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    map-underscore-to-camel-case: true

#自定义参数
